FROM golang:1.19

WORKDIR /app

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

COPY . /app/

EXPOSE 8091

CMD [ "air", "serve", "--http", "0.0.0.0:8091", "--debug", "--dir", "/pb_data"]
